# Combine Original and Filled Sector Data and Screener Data

Combine data sources

In [44]:
# Packages
import pandas as pd

## Original Data

In [45]:
# US Stocks data
# '~\Box\STAT 222 Capstone\Raw Data\US Public Companies Classification\US_stocks.csv'
us_stocks = pd.read_csv('~/Box/STAT 222 Capstone/Raw Data/US Public Companies Classification/US_stocks.csv')
us_stocks

,Ticker,Description,Company Name,Sector,Industry Group,Industry,Sub-Industry,Comment
0,CTVA,"Corteva, Inc. is a global provider of seed and...",CORTEVA INC,Materials,Materials,Chemicals,Fertilizers & Agricultural Chemicals,"Producers of fertilizers, pesticides, potash o..."
1,ALCO,"Alico, Inc. is an agribusiness and land manage...",ALICO INC,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Agricultural Products,Producers of agricultural products. Includes c...
2,LMNR,Limoneira Company is primarily an agribusiness...,LIMONEIRA CO,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Agricultural Products,Producers of agricultural products. Includes c...
3,SANW,S&W Seed Company (S&W) is a multi-crop and mid...,S&W SEED CO,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Agricultural Products,Producers of agricultural products. Includes c...
4,TRC,Tejon Ranch Co. is a diversified real estate d...,TEJON RANCH CO,Real Estate,Real Estate,Real Estate Management & Development,Diversified Real Estate Activities,Companies engaged in a diverse spectrum of rea...
...,...,...,...,...,...,...,...,...
3139,HON,Honeywell International Inc. is a software-ind...,HONEYWELL INTERNATIONAL INC,Industrials,Capital Goods,Industrial Conglomerates,Industrial Conglomerates,Diversified industrial companies with business...
3140,IEP,Icahn Enterprises L.P. is a diversified holdin...,ICAHN ENTERPRISES LP,Industrials,Capital Goods,Industrial Conglomerates,Industrial Conglomerates,Diversified industrial companies with business...
3141,SPLP,Steel Partners Holdings L.P. is a diversified ...,STEEL PARTNERS HOLDINGS LP,Industrials,Capital Goods,Industrial Conglomerates,Industrial Conglomerates,Diversified industrial companies with business...
3142,SEB,Seaboard Corporation is primarily engaged in h...,SEABOARD CORP,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Packaged Foods & Meats,Producers of packaged foods including dairy pr...
3143,BRK.B,Berkshire Hathaway Inc. is a holding company o...,BERKSHIRE HATHAWAY,Financials,Diversified Financials,Diversified Financial Services,Multi-Sector Holdings,A company with significantly diversified holdi...

## Filled Data

In [46]:
# Filled in values
# '~\Box\STAT 222 Capstone\Intermediate Data\Sectors\Missing_in_sector_data - Filled.csv'
filled = pd.read_csv('~/Box/STAT 222 Capstone/Intermediate Data/Sectors/Missing_in_sector_data - Filled.csv')
filled

    Symbol                  Sector
0      BCE  Communication Services
1      BEP                  Energy
2      CCJ                  Energy
3      CVE                  Energy
4      ENB                  Energy
..     ...                     ...
240   RELX  Information Technology
241    TAL  Consumer Discretionary
242   TRTN             Industrials
243   VLRS             Industrials
244    XIN             Real Estate

[245 rows x 2 columns]

In [47]:
# Rename Symbol to Ticker
filled = filled.rename(columns={'Symbol': 'Ticker'})

## Combine Original and Filled

In [48]:
# Combine the two dataframes by stacking them
combined = pd.concat([us_stocks, filled], axis=0)
combined

,Ticker,Description,Company Name,Sector,Industry Group,Industry,Sub-Industry,Comment
0,CTVA,"Corteva, Inc. is a global provider of seed and...",CORTEVA INC,Materials,Materials,Chemicals,Fertilizers & Agricultural Chemicals,"Producers of fertilizers, pesticides, potash o..."
1,ALCO,"Alico, Inc. is an agribusiness and land manage...",ALICO INC,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Agricultural Products,Producers of agricultural products. Includes c...
2,LMNR,Limoneira Company is primarily an agribusiness...,LIMONEIRA CO,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Agricultural Products,Producers of agricultural products. Includes c...
3,SANW,S&W Seed Company (S&W) is a multi-crop and mid...,S&W SEED CO,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Agricultural Products,Producers of agricultural products. Includes c...
4,TRC,Tejon Ranch Co. is a diversified real estate d...,TEJON RANCH CO,Real Estate,Real Estate,Real Estate Management & Development,Diversified Real Estate Activities,Companies engaged in a diverse spectrum of rea...
...,...,...,...,...,...,...,...,...
240,RELX,NaN,NaN,Information Technology,NaN,NaN,NaN,NaN
241,TAL,NaN,NaN,Consumer Discretionary,NaN,NaN,NaN,NaN
242,TRTN,NaN,NaN,Industrials,NaN,NaN,NaN,NaN
243,VLRS,NaN,NaN,Industrials,NaN,NaN,NaN,NaN
244,XIN,NaN,NaN,Real Estate,NaN,NaN,NaN,NaN

## Screener Data

In [49]:
# Load '~\Box\STAT 222 Capstone\Raw Data\Screener\nasdaq_screener_1711519842163.csv'
nasdaq_screener = pd.read_csv('~/Box/STAT 222 Capstone/Raw Data/Screener/nasdaq_screener_1711519842163.csv')
nasdaq_screener

,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,Sector,Industry
0,A,Agilent Technologies Inc. Common Stock,$144.41,-1.1500,-0.79%,4.232011e+10,United States,1999.0,2021029,Industrials,Biotechnology: Laboratory Analytical Instruments
1,AA,Alcoa Corporation Common Stock,$31.58,-0.2800,-0.879%,5.670473e+09,United States,2016.0,3763089,Industrials,Aluminum
2,AACG,ATA Creativity Global American Depositary Shares,$1.02,-0.0400,-3.774%,3.225461e+07,China,2008.0,7323,Real Estate,Other Consumer Services
3,AACI,Armada Acquisition Corp. I Common Stock,$11.07,0.0100,0.09%,0.000000e+00,United States,2021.0,6393,Finance,Blank Checks
4,AACIU,Armada Acquisition Corp. I Unit,$11.51,0.0000,0.00%,0.000000e+00,United States,2021.0,4,Finance,Blank Checks
...,...,...,...,...,...,...,...,...,...,...,...
7188,ZVRA,Zevra Therapeutics Inc. Common Stock,$5.72,0.0800,1.418%,2.071679e+08,United States,NaN,188092,Health Care,Biotechnology: Pharmaceutical Preparations
7189,ZVSA,ZyVersa Therapeutics Inc. Common Stock,$0.7491,-0.0509,-6.363%,9.313540e+05,United States,2022.0,453819,Health Care,Biotechnology: Pharmaceutical Preparations
7190,ZWS,Zurn Elkay Water Solutions Corporation Common ...,$32.31,-0.0100,-0.031%,5.557195e+09,United States,2012.0,559464,Industrials,Industrial Machinery/Components
7191,ZYME,Zymeworks Inc. Common Stock,$10.47,0.0700,0.673%,7.388493e+08,United States,NaN,345275,Health Care,Biotechnology: Pharmaceutical Preparations
7192,ZYXI,Zynex Inc. Common Stock,$12.35,-0.3900,-3.061%,3.973017e+08,United States,NaN,143976,Health Care,Biotechnology: Electromedical & Electrotherape...

In [50]:
# Keep Symbol, Name, Country, IPO Year, Sector, Industry
nasdaq_screener = nasdaq_screener[['Symbol', 'Name', 'Country', 'IPO Year', 'Sector', 'Industry']]
# Rename Sector to Screener_Sector, Industry to Screener_Industry, Symbol to Ticker
nasdaq_screener = nasdaq_screener.rename(columns={'Sector': 'Screener_Sector', 'Industry': 'Screener_Industry', 'Symbol': 'Ticker'})
# Merge combined and nasdaq_screener on Ticker
combined = pd.merge(combined, nasdaq_screener, on='Ticker', how='left')
combined

,Ticker,Description,Company Name,Sector,Industry Group,Industry,Sub-Industry,Comment,Name,Country,IPO Year,Screener_Sector,Screener_Industry
0,CTVA,"Corteva, Inc. is a global provider of seed and...",CORTEVA INC,Materials,Materials,Chemicals,Fertilizers & Agricultural Chemicals,"Producers of fertilizers, pesticides, potash o...",Corteva Inc. Common Stock,United States,2019.0,Consumer Staples,Farming/Seeds/Milling
1,ALCO,"Alico, Inc. is an agribusiness and land manage...",ALICO INC,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Agricultural Products,Producers of agricultural products. Includes c...,Alico Inc. Common Stock,United States,NaN,NaN,NaN
2,LMNR,Limoneira Company is primarily an agribusiness...,LIMONEIRA CO,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Agricultural Products,Producers of agricultural products. Includes c...,Limoneira Co Common Stock,United States,NaN,Consumer Staples,Farming/Seeds/Milling
3,SANW,S&W Seed Company (S&W) is a multi-crop and mid...,S&W SEED CO,Consumer Staples,"Food, Beverage & Tobacco",Food Products,Agricultural Products,Producers of agricultural products. Includes c...,S&W Seed Company Common Stock (NV),United States,NaN,Consumer Staples,Farming/Seeds/Milling
4,TRC,Tejon Ranch Co. is a diversified real estate d...,TEJON RANCH CO,Real Estate,Real Estate,Real Estate Management & Development,Diversified Real Estate Activities,Companies engaged in a diverse spectrum of rea...,Tejon Ranch Co Common Stock,United States,2000.0,Finance,Real Estate
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3384,RELX,NaN,NaN,Information Technology,NaN,NaN,NaN,NaN,RELX PLC PLC American Depositary Shares (Each ...,United Kingdom,2015.0,Consumer Discretionary,Business Services
3385,TAL,NaN,NaN,Consumer Discretionary,NaN,NaN,NaN,NaN,TAL Education Group American Depositary Shares,China,NaN,Real Estate,Other Consumer Services
3386,TRTN,NaN,NaN,Industrials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3387,VLRS,NaN,NaN,Industrials,NaN,NaN,NaN,NaN,Controladora Vuela Compania de Aviacion S.A.B....,NaN,2013.0,Consumer Discretionary,Air Freight/Delivery Services
3388,XIN,NaN,NaN,Real Estate,NaN,NaN,NaN,NaN,Xinyuan Real Estate Co Ltd American Depositary...,China,2007.0,Consumer Discretionary,Homebuilding

In [51]:
# Count NaN values in Screener_Sector and Screener_Industry
print('obs missing Screener_Sector:', combined['Screener_Sector'].isna().sum())
print('obs missing Screener_Industry:', combined['Screener_Industry'].isna().sum())
# Count obs missing Sub-Industry
print('obs missing Sub-Industry:', combined['Sub-Industry'].isna().sum())

obs missing Screener_Sector: 475
obs missing Screener_Industry: 475
obs missing Sub-Industry: 245

Screener is missing a ton of companies, so not very useful. The screener sector values also seem inaccurate.

## Limit variables to just Ticker and Sector

In [52]:
combined = combined[['Ticker', 'Sector']]
# Check for missing values
print('obs missing Sector:', combined['Sector'].isna().sum())
combined

obs missing Sector: 0

     Ticker                  Sector
0      CTVA               Materials
1      ALCO        Consumer Staples
2      LMNR        Consumer Staples
3      SANW        Consumer Staples
4       TRC             Real Estate
...     ...                     ...
3384   RELX  Information Technology
3385    TAL  Consumer Discretionary
3386   TRTN             Industrials
3387   VLRS             Industrials
3388    XIN             Real Estate

[3389 rows x 2 columns]

## Final Output

In [53]:
# Output
# '~\Box\STAT 222 Capstone\Intermediate Data\Sectors\combined_sector_data.csv'
combined.to_csv('~/Box/STAT 222 Capstone/Intermediate Data/Sectors/combined_sector_data.csv', index=False)