In [2]:
import pandas as pd
import requests

# Load the CSV file into a pandas DataFrame
df = pd.read_csv("~/Box/STAT 222 Capstone/Intermediate Data/Credit_Rating/combined_credit_rating_data.csv")

# Extract all distinct "Symbol" values
distinct_symbols = df["Symbol"].unique()

# Convert the array of distinct symbols to a pandas list
distinct_symbols_list = distinct_symbols.tolist()

distinct_symbols_list

['BCE',
 'BEP',
 'CCJ',
 'COST',
 'CVE',
 'CVX',
 'ENB',
 'FICO',
 'FTS',
 'GOLD',
 'IMO',
 'JWN',
 'MCK',
 'MGA',
 'MUR',
 'SJR',
 'SYY',
 'TAC',
 'TECK',
 'TOT',
 'VALE',
 'AA',
 'AAL',
 'AAP',
 'ABB',
 'ABC',
 'ABG',
 'ABT',
 'ACCO',
 'ADI',
 'ADM',
 'AEE',
 'AEP',
 'AGCO',
 'AIN',
 'ALB',
 'AMGN',
 'AMKR',
 'AMX',
 'AMZN',
 'ANDE',
 'ANTM',
 'AON',
 'APA',
 'APD',
 'ARW',
 'ATI',
 'ATO',
 'AVA',
 'AVGO',
 'AVT',
 'AVY',
 'AWK',
 'AWR',
 'AXL',
 'AZO',
 'BAX',
 'BC',
 'BDX',
 'BG',
 'BGC',
 'BGG',
 'BIIB',
 'BIO',
 'BKD',
 'BKR',
 'BLL',
 'BMRN',
 'BMY',
 'BSX',
 'BTU',
 'BUD',
 'BWA',
 'BYD',
 'BZH',
 'CAG',
 'CAH',
 'CAT',
 'CBB',
 'CBT',
 'CCEP',
 'CCI',
 'CCK',
 'CDE',
 'CENT',
 'CENX',
 'CHE',
 'CHH',
 'CHK',
 'CHTR',
 'CIEN',
 'CKH',
 'CL',
 'CLW',
 'CMC',
 'CMI',
 'CMS',
 'CNHI',
 'CNI',
 'COP',
 'CPB',
 'CR',
 'CRS',
 'CSCO',
 'CSL',
 'CSX',
 'CTAS',
 'CTB',
 'CVA',
 'CVS',
 'CXO',
 'CXW',
 'CZR',
 'D',
 'DAL',
 'DAN',
 'DCP',
 'DE',
 'DEO',
 'DGX',
 'DHI',
 'DHR',
 'DLX',
 'DNR',
 'DOV',
 'DRI',
 'DTE',
 'DUK',
 'DVA',
 'DVN',
 'E',
 'EBAY',
 'ECL',
 'EE',
 'EFX',
 'EIX',
 'EME',
 'EMN',
 'EMR',
 'ENDP',
 'ENR',
 'EOG',
 'EPAY',
 'EPD',
 'EQIX',
 'EQR',
 'EQT',
 'ES',
 'ETN',
 'ETR',
 'EXC',
 'EXPE',
 'FCX',
 'FDX',
 'FE',
 'FISV',
 'FLR',
 'FLS',
 'FMC',
 'FOE',
 'GATX',
 'GD',
 'GE',
 'GILD',
 'GIS',
 'GLW',
 'GM',
 'GPS',
 'GSK',
 'GWRS',
 'HAL',
 'HAS',
 'HBI',
 'HCA',
 'HES',
 'HFC',
 'HLT',
 'HLX',
 'HNGR',
 'HOG',
 'HON',
 'HOV',
 'HPQ',
 'HRB',
 'HRL',
 'HSC',
 'HSY',
 'HTZ',
 'IDA',
 'IDCC',
 'IEX',
 'IGT',
 'INGR',
 'INSW',
 'INTC',
 'INTU',
 'IP',
 'IPG',
 'IPI',
 'IRM',
 'IT',
 'ITW',
 'JBHT',
 'JBL',
 'JBLU',
 'JCI',
 'JNJ',
 'JNPR',
 'JOUT',
 'K',
 'KHC',
 'KMB',
 'KMT',
 'KOF',
 'KSS',
 'LB',
 'LEA',
 'LEU',
 'LII',
 'LLY',
 'LMT',
 'LNT',
 'LSXMA',
 'LUV',
 'MAN',
 'MAS',
 'MCHP',
 'MDC',
 'MDLZ',
 'MDT',
 'MGM',
 'MHK',
 'MHO',
 'MKC',
 'MLM',
 'MMC',
 'MMM',
 'MMP',
 'MOS',
 'MRO',
 'MSFT',
 'MSI',
 'MTOR',
 'MTZ',
 'NAV',
 'NBR',
 'NDAQ',
 'NE',
 'NEE',
 'NEO',
 'NFG',
 'NGG',
 'NI',
 'NKTR',
 'NOC',
 'NPO',
 'NRG',
 'NSC',
 'NUE',
 'NVS',
 'NWE',
 'NWL',
 'NWN',
 'OAS',
 'OC',
 'OGE',
 'OKE',
 'OLN',
 'OMC',
 'OMI',
 'ORCL',
 'ORLY',
 'OTTR',
 'OXY',
 'PAA',
 'PBI',
 'PCAR',
 'PCG',
 'PDCO',
 'PDLI',
 'PED',
 'PEG',
 'PEP',
 'PFE',
 'PH',
 'PHG',
 'PKI',
 'PM',
 'PNM',
 'PNR',
 'PNW',
 'POL',
 'PPC',
 'PPG',
 'PPL',
 'PSX',
 'PVH',
 'PXD',
 'RAD',
 'RIG',
 'RIO',
 'ROK',
 'ROP',
 'RPM',
 'RRC',
 'RRD',
 'RS',
 'RSG',
 'RYN',
 'SBGI',
 'SBUX',
 'SCCO',
 'SCI',
 'SGU',
 'SHW',
 'SLB',
 'SLGN',
 'SMG',
 'SNA',
 'SON',
 'SPGI',
 'SPWR',
 'SPXC',
 'SR',
 'SRE',
 'STLD',
 'STZ',
 'SWK',
 'SWX',
 'SYK',
 'T',
 'TEF',
 'TEL',
 'TEN',
 'TER',
 'TEX',
 'TGT',
 'THC',
 'TKR',
 'TMO',
 'TMUS',
 'TOL',
 'TRI',
 'TRN',
 'TUP',
 'TXN',
 'TXT',
 'UFS',
 'UGI',
 'UHS',
 'UIS',
 'UNH',
 'UNP',
 'UPS',
 'URI',
 'USM',
 'UVV',
 'VFC',
 'VGR',
 'VIAV',
 'VLO',
 'VMC',
 'VRSK',
 'VRTX',
 'VZ',
 'WBA',
 'WEC',
 'WEN',
 'WFRD',
 'WHR',
 'WLL',
 'WMB',
 'WOR',
 'WPP',
 'WY',
 'WYNN',
 'X',
 'XEC',
 'XEL',
 'XOM',
 'XRX',
 'YRCW',
 'YUM',
 'ACH',
 'ADT',
 'AES',
 'AGR',
 'ALSN',
 'ALTR',
 'AMCR',
 'AMD',
 'AMOV',
 'ARCO',
 'ASML',
 'AUY',
 'AZN',
 'BABA',
 'BAK',
 'BIDU',
 'BKH',
 'BP',
 'BR',
 'BRFS',
 'BTI',
 'BURL',
 'CAL',
 'CCU',
 'CDNS',
 'CLX',
 'CMCSA',
 'CNR',
 'COMP',
 'CPAC',
 'CRESY',
 'CSIQ',
 'CYH',
 'DELL',
 'DXC',
 'EAT',
 'ERJ',
 'FCAU',
 'FIS',
 'FLEX',
 'FLO',
 'FMS',
 'GGB',
 'HII',
 'HMC',
 'HMHC',
 'HPE',
 'IRCP',
 'ITT',
 'KEP',
 'KEX',
 'KGC',
 'KOS',
 'KRO',
 'LEN',
 'LVS',
 'MDU',
 'MEOH',
 'MPC',
 'MPLX',
 'MTH',
 'NBL',
 'NEU',
 'NGL',
 'NLSN',
 'NOK',
 'NVDA',
 'ORAN',
 'PHI',
 'PKX',
 'PTR',
 'PYPL',
 'RCI',
 'SANM',
 'SBS',
 'SIG',
 'SKM',
 'SNY',
 'SONY',
 'STM',
 'STX',
 'SWN',
 'TDG',
 'TDS',
 'TEVA',
 'TIF',
 'TIGO',
 'TKC',
 'TSN',
 'VEON',
 'VIA',
 'WCN',
 'WLK',
 'IBA',
 'ENT',
 'AAPL',
 'ABBV',
 'ABEV',
 'ACHC',
 'ACIW',
 'ACM',
 'ACN',
 'ADS',
 'AIR',
 'ALE',
 'ALJ',
 'ALLE',
 'ALR',
 'AMAT',
 'AMCX',
 'AMP',
 'APH',
 'ARC',
 'ASH',
 'AT',
 'ATVI',
 'AWI',
 'AXTA',
 'BA',
 'BAH',
 'BBBY',
 'BCC',
 'BDC',
 'BERY',
 'BFAM',
 'BHE',
 'BLDR',
 'BTE',
 'CACI',
 'CAJ',
 'CAR',
 'CCLP',
 'CCOI',
 'CCZ',
 'CDK',
 'CDW',
 'CE',
 'CEIX',
 'CEVA',
 'CFX',
 'CHDN',
 'CHEF',
 'CLF',
 'CLMT',
 'CMCO',
 'CMLS',
 'CMP',
 'CNC',
 'CNQ',
 'CNSL',
 'COMM',
 'COTY',
 'CPE',
 'CPLP',
 'CPS',
 'CRC',
 'CRI',
 'CRK',
 'CRL',
 'CSGS',
 'CSV',
 'CVGI',
 'CVI',
 'CWST',
 'DAR',
 'DBD',
 'DG',
 'DGI',
 'DISH',
 'DLTR',
 'DOOR',
 'EC',
 'EGO',
 'EL',
 'ENIA',
 'ENS',
 'ENTG',
 'EPC',
 'ETM',
 'EVA',
 'EVC',
 'EW',
 'EXP',
 'EXPR',
 'FANG',
 'FBHS',
 'FCN',
 'FET',
 'FLOW',
 'FLT',
 'FRGI',
 'FRP',
 'FTI',
 'FUN',
 'G',
 'GAP',
 'GCI',
 'GEF',
 'GEL',
 'GFF',
 'GFI',
 'GHC',
 'GLDD',
 'GLP',
 'GLPG',
 'GOGO',
 'GOOG',
 'GOOGL',
 'GPI',
 'GPN',
 'GPOR',
 'GPRE',
 'GRFS',
 'GSL',
 'GTN',
 'GXP',
 'H',
 'HBM',
 'HCHC',
 'HEES',
 'HEP',
 'HL',
 'HMTV',
 'HOLX',
 'HUBG',
 'HUM',
 'HUN',
 'HXL',
 'ICLR',
 'III',
 'IMKTA',
 'INFO',
 'IO',
 'JAZZ',
 'KALU',
 'KAR',
 'KBH',
 'KODK',
 'KOP',
 'KRA',
 'KSU',
 'KTOS',
 'L',
 'LAMR',
 'LCI',
 'LDOS',
 'LEE',
 'LGF',
 'LH',
 'LKQ',
 'LPI',
 'LPX',
 'LRCX',
 'LSCC',
 'LXU',
 'LYB',
 'LYV',
 'MA',
 'MANT',
 'MBI',
 'MBT',
 'MDRX',
 'MEDP',
 'MERC',
 'MGEE',
 'MGI',
 'MKL',
 'MMLP',
 'MO',
 'MRC',
 'MRK',
 'MSCI',
 'MT',
 'MTDR',
 'MTG',
 'MTN',
 'MTSC',
 'MTX',
 'MWA',
 'MX',
 'MYL',
 'NCR',
 'NFLX',
 'NGD',
 'NKE',
 'NNBR',
 'NS',
 'NTAP',
 'NVO',
 'NVR',
 'NX',
 'NXPI',
 'NYT',
 'OEC',
 'OGS',
 'OII',
 'OIS',
 'ON',
 'OSI',
 'OSK',
 'OTEX',
 'OXM',
 'PACB',
 'PAG',
 'PAHC',
 'PBFX',
 'PDC',
 'PDCE',
 'PDS',
 'PENN',
 'PGR',
 'PKG',
 'PLOW',
 'PMTS',
 'POR',
 'POST',
 'PRA',
 'PRAA',
 'PRE',
 'PRGO',
 'PSO',
 'QCOM',
 'RBA',
 'RCII',
 'RCL',
 'RDN',
 'RLI',
 'RYI',
 'SABR',
 'SAH',
 'SAIC',
 'SAP',
 'SBAC',
 'SBH',
 'SCHL',
 'SCS',
 'SEAS',
 'SEE',
 'SEM',
 'SFM',
 'SGH',
 'SGMS',
 'SHEL',
 'SITE',
 'SJM',
 'SMTC',
 'SO',
 'SPH',
 'SPWH',
 'SRI',
 'SSL',
 'SSNC',
 'STKL',
 'STON',
 'SXC',
 'TAK',
 'TAST',
 'TCS',
 'TECD',
 'TEO',
 'TFX',
 'TGI',
 'TGLS',
 'TGNA',
 'THS',
 'TILE',
 'TMS',
 'TPC',
 'TPX',
 'TRGP',
 'TRMB',
 'TROX',
 'TRS',
 'TSM',
 'TSQ',
 'TTC',
 'TTM',
 'TTMI',
 'TWI',
 'UGP',
 'UNIT',
 'V',
 'VC',
 'VIV',
 'VMI',
 'VOD',
 'VRNT',
 'VSAT',
 'VSH',
 'VSTO',
 'WAB',
 'WBT',
 'WCC',
 'WDC',
 'WNC',
 'WRB',
 'WU',
 'WWW',
 'XPO',
 'XRAY',
 'XYL',
 'Y',
 'YPF',
 'ZBRA',
 'ZTS',
 'ADNT',
 'ADP',
 'ADSK',
 'ADSW',
 'ALGT',
 'ALK',
 'ALKS',
 'ALV',
 'AMAG',
 'AMC',
 'AMRX',
 'AQN',
 'AR',
 'ASNA',
 'ATKR',
 'BAM',
 'BECN',
 'BIG',
 'BW',
 'CASA',
 'CATM',
 'CCL',
 'CF',
 'CLGX',
 'CLH',
 'CLR',
 'COO',
 'CP',
 'CWT',
 'DFIN',
 'DIS',
 'EA',
 'EPR',
 'FDP',
 'FL',
 'FTV',
 'GBX',
 'GCP',
 'GLT',
 'GME',
 'HDS',
 'HRC',
 'HST',
 'HZN',
 'IAC',
 'IBM',
 'ILMN',
 'IRDM',
 'IRS',
 'KEYS',
 'KMI',
 'KW',
 'MCO',
 'MDCA',
 'MIC',
 'MTSI',
 'MTW',
 'MU',
 'NEM',
 'NM',
 'NOG',
 'NRP',
 'NUAN',
 'OSB',
 'PFGC',
 'PRAH',
 'PSXP',
 'PTC',
 'QEP',
 'QRVO',
 'R',
 'RELX',
 'RFP',
 'RHP',
 'ROCK',
 'ROST',
 'SALM',
 'SAVE',
 'SLCA',
 'SM',
 'SPR',
 'SRCL',
 'SSP',
 'SUN',
 'TAL',
 'TRTN',
 'TSLA',
 'TWTR',
 'UAN',
 'VLRS',
 'VRSN',
 'VVV',
 'WM',
 'WRK',
 'WTI',
 'XIN',
 'XPER',
 'YORW']

In [ ]:
# API key for accessing the financial data
api_key = "test"

# Function to fetch financial statements data
def fetch_financial_statements(company):
    # Number of years for which data will be retrieved
    quarters = 67
    
    # Fetching balance sheet data
    balance_sheet = requests.get(f'https://financialmodelingprep.com/api/v3/balance-sheet-statement/{company}?period=quarter&limit={quarters}&apikey={api_key}')
    balance_sheet = balance_sheet.json()

    # Fetching income statement data
    income_statement = requests.get(f'https://financialmodelingprep.com/api/v3/income-statement/{company}?period=quarter&limit={quarters}&apikey={api_key}')
    income_statement = income_statement.json()
    
    # Fetching cash flow statement data
    cash_flow_statement = requests.get(f'https://financialmodelingprep.com/api/v3/cash-flow-statement/{company}?period=quarter&limit={quarters}&apikey={api_key}')
    cash_flow_statement = cash_flow_statement.json()

    return balance_sheet, income_statement, cash_flow_statement

# Initialize empty lists to store the fetched data
balance_sheet_data = []
income_statement_data = []
cash_flow_statement_data = []

i = 1
# Loop over the first 10 symbols in the list
for symbol in distinct_symbols_list:
    # Fetch financial statements data
    if i%20==0:
        print(i)
    i+=1
    balance_sheet, income_statement, cash_flow_statement = fetch_financial_statements(symbol)

    # Append fetched data to respective lists
    
    balance_sheet_data.extend(balance_sheet)
    income_statement_data.extend(income_statement)
    cash_flow_statement_data.extend(cash_flow_statement)

# Combine data into a single DataFrame
balance_sheet_df = pd.DataFrame(balance_sheet_data)
income_statement_df = pd.DataFrame(income_statement_data)
cash_flow_statement_df = pd.DataFrame(cash_flow_statement_data)

In [107]:
balance_sheet_df.to_csv("balance_sheet_df.csv")
income_statement_df.to_csv(("income_statement_df.csv"))
cash_flow_statement_df.to_csv("cash_flow_statement_df.csv")

In [6]:
balance = pd.read_csv(r"~\Box\STAT 222 Capstone\Intermediate Data\Tabular_Fin\tabuler_fin_data(balance_sheet).csv")
income = pd.read_csv(r"~\Box\STAT 222 Capstone\Intermediate Data\Tabular_Fin\tabuler_fin_data(income_statement).csv")
cash_flow = pd.read_csv(r"~\Box\STAT 222 Capstone\Intermediate Data\Tabular_Fin\tabuler_fin_data(cash_flow_statement).csv")

In [7]:
print(balance.shape, income.shape, cash_flow.shape)

(55377, 55) (55805, 39) (54808, 41)

In [9]:
balance.head()

,Unnamed: 0,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,cashAndCashEquivalents,...,totalStockholdersEquity,totalEquity,totalLiabilitiesAndStockholdersEquity,minorityInterest,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt,link,finalLink
0,0,2023-09-30,BCE,CAD,718940,2023-09-30,2023-09-29 20:00:00,2023,Q3,619000000.0,...,2.097000e+10,2.130700e+10,7.037200e+10,337000000.0,7.037200e+10,326000000.0,3.470300e+10,3.408400e+10,NaN,NaN
1,1,2023-06-30,BCE,CAD,718940,2023-06-30,2023-06-30 00:00:00,2023,Q2,900000000.0,...,2.112100e+10,2.144900e+10,7.004900e+10,328000000.0,7.004900e+10,322000000.0,3.435300e+10,3.345300e+10,NaN,NaN
2,2,2023-03-31,BCE,CAD,718940,2023-03-31,2023-03-31 00:00:00,2023,Q1,741000000.0,...,2.193400e+10,2.226700e+10,6.997500e+10,333000000.0,6.997500e+10,664000000.0,3.380300e+10,3.306200e+10,NaN,NaN
3,3,2022-12-31,BCE,CAD,718940,2022-12-31,2022-12-30 19:00:00,2022,Q4,149000000.0,...,2.217800e+10,2.251500e+10,6.932900e+10,337000000.0,6.932900e+10,608000000.0,3.192000e+10,3.177100e+10,NaN,NaN
4,4,2022-09-30,BCE,CAD,718940,2022-09-30,2022-09-29 20:00:00,2022,Q3,733000000.0,...,2.264100e+10,2.298100e+10,6.856000e+10,340000000.0,6.856000e+10,615000000.0,3.145300e+10,3.072000e+10,NaN,NaN

In [10]:
income.head()

,Unnamed: 0,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,revenue,...,incomeBeforeTaxRatio,incomeTaxExpense,netIncome,netIncomeRatio,eps,epsdiluted,weightedAverageShsOut,weightedAverageShsOutDil,link,finalLink
0,0,2023-09-30,BCE,CAD,718940,2023-09-30,2023-09-29 20:00:00,2023,Q3,6.080000e+09,...,0.156250,243000000.0,687000000.0,0.112993,0.70,0.70,912300000.0,912300000.0,NaN,NaN
1,1,2023-06-30,BCE,CAD,718940,2023-06-30,2023-06-30 00:00:00,2023,Q2,6.066000e+09,...,0.110452,273000000.0,375000000.0,0.061820,0.37,0.37,912200000.0,912500000.0,NaN,NaN
2,2,2023-03-31,BCE,CAD,718940,2023-03-31,2023-03-31 00:00:00,2023,Q1,6.054000e+09,...,0.174760,270000000.0,771000000.0,0.127354,0.79,0.79,912100000.0,912300000.0,NaN,NaN
3,3,2022-12-31,BCE,CAD,718940,2022-12-31,2022-12-30 19:00:00,2022,Q4,6.439000e+09,...,0.122535,222000000.0,572000000.0,0.088834,0.58,0.58,912000000.0,912200000.0,NaN,NaN
4,4,2022-09-30,BCE,CAD,718940,2022-09-30,2022-09-29 20:00:00,2022,Q3,6.024000e+09,...,0.157537,178000000.0,715000000.0,0.118692,0.83,0.83,911900000.0,912300000.0,NaN,NaN

In [11]:
cash_flow.head()

,Unnamed: 0,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,netIncome,...,netCashUsedProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow,link,finalLink
0,0,2023-09-30,BCE,CAD,718940,2023-09-30,2023-09-29 20:00:00,2023,Q3,707000000.0,...,-1.066000e+09,0.0,-281000000.0,619000000.0,900000000.0,1.961000e+09,-1.162000e+09,799000000.0,NaN,NaN
1,1,2023-06-30,BCE,CAD,718940,2023-06-30,2023-06-30 00:00:00,2023,Q2,397000000.0,...,-7.500000e+08,-360000000.0,-201000000.0,450000000.0,651000000.0,2.365000e+09,-1.452000e+09,913000000.0,NaN,NaN
2,2,2023-03-31,BCE,CAD,718940,2023-03-31,2023-03-31 00:00:00,2023,Q1,788000000.0,...,4.360000e+08,-40000000.0,552000000.0,651000000.0,99000000.0,1.247000e+09,-1.086000e+09,161000000.0,NaN,NaN
3,3,2022-12-31,BCE,CAD,718940,2022-12-31,2022-12-30 19:00:00,2022,Q4,567000000.0,...,-7.010000e+08,-3000000.0,-584000000.0,149000000.0,733000000.0,2.056000e+09,-1.638000e+09,418000000.0,NaN,NaN
4,4,2022-09-30,BCE,CAD,718940,2022-09-30,2022-09-29 20:00:00,2022,Q3,771000000.0,...,-5.270000e+08,0.0,137000000.0,733000000.0,596000000.0,1.996000e+09,-1.320000e+09,676000000.0,NaN,NaN